name: 'Bug Report'
description: 'Report a bug to help us improve Commander'
labels:
  - 'kind/bug'
  - 'status/need-triage'
body:
  - type: 'markdown'
    attributes:
      value: |-
        > [!IMPORTANT]
        > Thanks for taking the time to fill out this bug report!
        >
        > Please search **[existing issues](https://github.com/autohandai/commander/issues)** to see if an issue already exists for the bug you encountered.

  - type: 'textarea'
    id: 'problem'
    attributes:
      label: 'What happened?'
      description: 'A clear and concise description of what the bug is.'
    validations:
      required: true

  - type: 'textarea'
    id: 'expected'
    attributes:
      label: 'What did you expect to happen?'
    validations:
      required: true

  - type: 'textarea'
    id: 'steps'
    attributes:
      label: 'Steps to reproduce'
      description: 'Provide detailed steps to reproduce the issue.'
      placeholder: |-
        1. Go to '...'
        2. Click on '...'
        3. Run command '...'
        4. See error
    validations:
      required: true

  - type: 'textarea'
    id: 'info'
    attributes:
      label: 'System information'
      description: 'Please provide your system information. Include OS version, Commander version, and any relevant environment details.'
      value: |-
        <details>

        ```
        OS: [e.g., macOS 14.5, Windows 11, Ubuntu 22.04]
        Commander Version: [e.g., 1.0.0]
        Node Version: [if applicable]
        Bun Version: [if applicable]
        ```

        </details>
    validations:
      required: true

  - type: 'textarea'
    id: 'logs'
    attributes:
      label: 'Error logs'
      description: 'If applicable, paste any error messages or logs here.'
      render: 'shell'

  - type: 'textarea'
    id: 'additional-context'
    attributes:
      label: 'Anything else we need to know?'
      description: 'Add any other context about the problem here, such as screenshots or configuration files.'
