// Service-specific tests
pub mod agent_status_service;
pub mod app_settings;
pub mod autohand_acp;
pub mod autohand_rpc;
pub mod cli_command_builder;
pub mod cli_output_service;
pub mod codex_sdk_service;
pub mod execution_mode_service;
pub mod file_service;
pub mod git_service_enhanced;
pub mod prompt_service;
pub mod recent_projects;
